### PR TITLE
Update azuredeploySpringStandard.bicep

### PR DESCRIPTION
**Pull request by zhangRon075**
Bug fixing: https://msazure.visualstudio.com/AzureDMSS/_workitems/edit/14193434/?triage=true 
Comments need to be add for specific name value like "The only supported value is 'default'"

### CODE REVIEW

**Comment by KarlErickson** [comment]
@kriation please review when you get a chance. Thanks!

**Comment by KarlErickson** [comment]
@kriation ping. Also, the repo name still needs updating. Thanks!

**Review by kriation — CHANGES_REQUESTED** [review]
@zhangRon075, for best practice, can the comment be added above the key:value pair instead of in-line? For example:
```
// The only supported value is 'default'
name: 'default'
```

**Comment by kriation** [comment]
Closing as #137 supersedes this PR

**Pull request closed without merging**
